In [1]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [2]:
#Поменять форму массива arr можно с помощью 
# присвоения атрибуту shape кортежа с желаемой формой:

arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
#Чтобы оставить исходный массив без изменений и дополнительно 
# получить новый массив новой формы, нужно использовать 
# функцию reshape. Она также принимает в качестве аргумента 
# кортеж из чисел для формы, но возвращает новый массив, 
# а не изменяет исходный:

arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
#У функции reshape есть дополнительный именованный аргумент order. 
# Он задаёт принцип, по которому элементы заполняют массив новой формы. 
# Если order='C' (по умолчанию), массив заполняется по строкам, 
# как в примере выше. 
# Если order='F', массив заполняется числами по столбцам:

arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [7]:
#Транспонирование - Эта операция меняет строки и столбцы массива местами.
#В NumPy эту операцию совершает функция transpose.

#Будем работать с двумерным массивом:

arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
#Транспонируем его:

arr_trans = arr.transpose()
arr_trans


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [8]:
#При транспонировании одномерного массива его форма не меняется:

arr = np.arange(3)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


In [9]:
#ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

#Создадим массив из шести чисел:

arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])
#Обратиться к его элементу по индексу можно так же, как и к списку:

print(arr[2])
# 1.4
#Привычная запись для срезов работает и для одномерных массивов:

print(arr[2:4])
# [1.4 1.6]
#Наконец, напечатать массив в обратном порядке можно с помощью 
# привычной конструкции [::-1]:

print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


In [10]:
#С многомерными массивами работать немного интереснее. 
# Создадим двумерный массив из одномерного:

nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [11]:
#Можно воспользоваться привычной записью нескольких 
# индексов в нескольких квадратных скобках:

nd_array[1][2]

3.0

In [12]:
#в одних и тех же квадратных скобках перечислить индексы через запятую:

nd_array[1, 2]

3.0

In [13]:
#Также через запятую можно передавать срезы 
# или даже их комбинации с индексами. 
# Например, получим 
# все элементы из колонки 3 для первых двух строк:

nd_array[:2, 2]

array([1., 3.])

In [14]:
#Можно применять срезы сразу и к строкам, и к столбцам:

nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [15]:
#Чтобы получить все значения из какой-то оси, 
# можно оставить на её месте двоеточие. 
# Например, из всех строк получим срез с третьего по четвёртый столбцы:

nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [17]:
#Чтобы получить самую последнюю ось 
# (в данном случае все столбцы), 
# двоеточие писать необязательно. 
# Строки будут получены целиком по умолчанию:

nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [ ]:
#Задание 7.2

try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery
    
# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = None
elem_5_3 = mystery[4,2]
# В переменную last сохраните элемент из последней строки последнего столбца
last = None
last = mystery[-1,-1]
# В переменную line_4 сохраните строку 4
line_4 = None
line_4 = mystery[3]
# В переменную col_2 сохраните предпоследний столбец
col_2 = None
col_2 = mystery[:,-2]
# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# Результат сохраните в переменную part
part = None
part = mystery[1:4,2:5]
#  Сохраните в переменную rev последний столбец в обратном порядке
rev = None
a = mystery[:,-1]
rev = a[::-1]
# Сохраните в переменную trans транспонированный массив
trans = None
trans = mystery.transpose()

In [20]:
#СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

# функция .sort

#Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:

arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [21]:
#Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:

arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

None
[ 3  4 12 12 15 23 23 45]


In [32]:
#РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ

data = np.array([4, 9, -4, 3,-5])
#Воспользуемся встроенной в NumPy функцией sqrt, 
# чтобы посчитать квадратные корни из элементов.

roots = np.sqrt(data)
roots

C:\Users\User\AppData\Local\Temp\ipykernel_6800\1272944308.py:7: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081,        nan])

In [23]:
# nan  Он расшифровывается как Not a number (не число). 
# Этот объект аналогичен встроенному типу None, 
# но имеет несколько отличий:
#Отличие 1. None является отдельным объектом типа NoneType. np.nan — это отдельный представитель класса float:

print(type(None))
# <class 'NoneType'>
print(type(np.nan))
# <class 'float'>
type(np.nan)

<class 'NoneType'>
<class 'float'>


float

In [24]:
#Отличие 2. None могут быть равны друг другу, а np.nan — нет:

print(None == None)
# True
print(np.nan == np.nan)
# False
#Как вы помните, чтобы грамотно сравнить что-либо с None, необходимо использовать оператор is. Это ещё более актуально для np.nan. Однако None даже через is не является эквивалентным np.nan:

print(None is None)
# True
print(np.nan is np.nan)
# True
print(np.nan is None)
# False

True
False
True
True
False


In [33]:
#Если попробовать посчитать сумму массива, 
# который содержит np.nan, в итоге получится nan:
sum(roots)

nan

In [34]:
#Что же делать?

#Можно заполнить пропущенные значения, например, нулями. 
# Для этого с помощью функции np.isnan(<массив>) узнаем, 
# на каких местах в массиве находятся «не числа»:

np.isnan(roots)

array([False, False,  True, False,  True])

In [35]:
#Можно использовать полученный массив из True и False 
# для извлечения элементов из массива roots, 
# на месте которых в булевом массиве указано True. 
# Таким способом можно узнать сами элементы, которые удовлетворяют условию np.isnan:

roots[np.isnan(roots)]

array([nan, nan])

In [28]:
#Этим элементам можно присвоить новые значения, например 0:

roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [29]:
#После этого, если пропущенных значений больше нет,
# можем подсчитать сумму элементов массива:

sum(roots)

6.732050807568877

In [31]:
np.isnan(np.nan)

True

In [ ]:
#Задание Задание 7.4

try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery
import numpy as np

# Получите булевый массив с информацией о np.nan 
# в массиве mystery
# True - значение пропущено, 
# False - значение не пропущено
nans_index = None
nans_index = np.isnan(mystery)

# В переменную n_nan сохраните число пропущенных значений
n_nan = None
n_nan = len(nans_index[np.isnan(mystery)])

# Заполните пропущенные значения в массиве mystery нулями
mystery[np.isnan(mystery)] = 0


# Поменяйте тип данных в массиве mystery на int32
mystery = np.int32(mystery)


# Отсортируйте значения в массиве по возрастанию и сохраните
# результат в переменную array
array = None
array = np.sort(mystery)
# Сохраните в массив table двухмерный массив, полученный из массива array
# В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
# по столбцам! Например, 1, 2, 3, 4 -> 1    3
#                                      2    4
table = None
table = array.reshape((5, 3), order='F')
#  Сохраните в переменную col средний столбец из table
col = None
col = table[:,1]