In [1]:
# СЛУЧАЙНЫЕ ЧИСЛА В NUMPY

# ГЕНЕРАЦИЯ FLOAT

# Для генерации псевдослучайных чисел в NumPy существует подмодуль random.

#Самой «базовой» функцией в нём можно считать функцию rand. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

import numpy as np
np.random.rand()

0.6274450473407642

In [7]:
# Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:

np.random.rand() * 100

16.06479903655097

In [10]:
# На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов через запятую целые числа, которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:

np.random.rand(5)

array([0.23286575, 0.91070903, 0.27999692, 0.0048704 , 0.78119244])

In [16]:
# Массив из двух случайных строк и трёх столбцов:

np.random.rand(2, 3)

array([[0.40651633, 0.31479559, 0.88558934],
       [0.17976823, 0.10615043, 0.26099086]])

In [ ]:
# Функция rand может принимать неограниченное число целых чисел для задания формы массива:

np.random.rand(2, 3, 4, 10)

# Обратите внимание, что обычно форму массивов мы задавали в функциях NumPy одним числом или кортежем, а не перечисляли её в виде аргументов через запятую.

In [3]:
# Если передать в rand кортеж, возникнет ошибка:

shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [4]:
# Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:

shape = (3, 4)
np.random.rand(*shape)

array([[0.82844151, 0.12373461, 0.83185081, 0.22935784],
       [0.22547756, 0.61832216, 0.18677143, 0.40590085],
       [0.18054439, 0.95538109, 0.95227354, 0.96065904]])

In [24]:
#Но в NumPy есть и другая 
# функция, генерирующая массивы случайных чисел от 0 до 1, 
# которая принимает в качестве аргумента именно кортеж без распаковки. 
# Она называется sample:

shape = (2, 3)
np.random.sample(shape)

# Возможно, именно функция sample покажется вам удобнее, 
# поскольку информацию о форме массива 
# обычно удобнее хранить в коде в виде кортежа
# и не задумываться потом о его распаковке. 
# В остальном функция sample не отличается от rand.

array([[0.31983088, 0.42325145, 0.79880056],
       [0.3772742 , 0.18577547, 0.94028706]])

In [11]:
#Не всегда требуются числа в диапазоне именно от 0 до 1.
# На самом деле с помощью специальных формул
# можно из диапазона от 0 до 1 получить
# любой другой желаемый диапазон,
# однако это не требуется делать самостоятельно
# — в NumPy доступна функция uniform:

np.random.uniform(low=0.0, high=1.0, size=(5,5))

#Первые два аргумента — нижняя и верхняя границы диапазона
# в формате float, третий опциональный аргумент — форма массива
# (если не задан, возвращается одно число).
# Форма массива задаётся кортежем или одним числом.

array([[0.47049608, 0.86765369, 0.78472438, 0.28437159, 0.50742498],
       [0.41756829, 0.06765565, 0.40225763, 0.75966224, 0.66969102],
       [0.18601835, 0.06671981, 0.71764583, 0.53560162, 0.75775221],
       [0.64140813, 0.56055233, 0.00636632, 0.41168359, 0.14995651],
       [0.21736373, 0.89264427, 0.63979987, 0.4544018 , 0.13035581]])

In [13]:
# Запуск без аргументов эквивалентен работе функций rand или sample:

np.random.uniform()

0.30077156253625836

In [33]:
# Зададим границы диапазона от -30 до 50:

np.random.uniform(-30, 50)

44.37862630044346

In [35]:
# Получим пять чисел в интервале от 0.5 до 0.75:

np.random.uniform(0.5, 0.75, size=5)

array([0.63250748, 0.50257155, 0.74366109, 0.56519248, 0.66222094])

In [39]:
# Получим массив из двух строк и трёх столбцов
# из чисел в интервале от -1000 до 500:

np.random.uniform(-1000, 500, size=(2, 3))

array([[ 407.94869934,  339.34870466, -697.52069826],
       [-552.96990493,  336.39803794, -785.18779455]])

In [ ]:
# ГЕНЕРАЦИЯ INT

#Не всегда требуется генерировать числа с плавающей точкой.
# Иногда бывает удобно получить целые числа int 
# (например, для поля игры в лото).
# Для генерации целых чисел используется функция random.randint:

randint(low, high=None, size=None, dtype=int)



In [43]:
#Функцию randint нельзя запустить совсем без параметров,
# необходимо указать хотя бы одно число.

#Если указан только аргумент low, 
# числа будут генерироваться от 0 до low-1,
# то есть верхняя граница не включается.

# Если задать low и high, числа будут генерироваться от low (включительно)
# до high (не включительно).

# size задаёт форму массива уже привычным для вас образом:
# одним числом — для одномерного или кортежем — для многомерного.

# dtype позволяет задать конкретный тип данных,
# который должен быть использован в массиве.

# Сгенерируем таблицу 2x3 от 0 до 3 включительно:

np.random.randint(4, size=(2,3))

array([[1, 3, 3],
       [2, 1, 0]])

In [49]:
#Чтобы задать и нижнюю, и верхнюю границы самостоятельно,
# передадим два числа, а затем форму:

np.random.randint(6, 12, size=(3,3))

array([[ 8,  8,  7],
       [11,  6,  7],
       [ 9, 10,  8]])

In [60]:
#ГЕНЕРАЦИЯ ВЫБОРОК

# Случайные числа можно использовать и для работы
# с уже существующими данными.
# Иногда для проверки гипотез о данных бывает
# удобно перемешать значения, чтобы проверить,
# является ли наблюдаемая закономерность случайной.

# Просто перемешать все числа в массиве позволяет функция random.shuffle.

# Возьмём массив из целых чисел от 0 до 5 и перемешаем его:

arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr

# Функция random.shuffle перемешивает тот массив,
# к которому применяется, и возвращает None.

[0 1 2 3 4 5]
None


array([0, 2, 5, 1, 3, 4])

In [70]:
#Чтобы получить новый перемешанный массив,
# а исходный оставить без изменений,
# можно использовать функцию random.permutation.
# Она принимает на вход один аргумент —
# или массив целиком,
# или одно число:

playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)

# Обратите внимание, что необязательно передавать
# в функцию сразу массив: в этот раз мы передали
# в качестве аргумента список и ошибки не возникло.
# При этом на выходе получился уже NumPy-массив
# (это заметно по отсутствию запятых при печати массива).
# Сам список playlist при этом остался без изменений.

['Deep Purple' 'ACDC' 'The Beatles' 'Pink Floyd']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [75]:
#Перемешать набор чисел от 0 до n-1 можно с помощью записи
# np.random.permutation(n)
# где n — верхняя граница, которая бы использовалась
# для генерации набора чисел функцией arange.

np.random.permutation(10)

# По сути, вначале создаётся массив из чисел с помощью arange,
# а затем он перемешивается. С помощью permutation
# можно избежать совершения этого дополнительного действия.

array([8, 3, 5, 6, 1, 0, 7, 4, 9, 2])

In [84]:
# Чтобы получить случайный набор объектов из массива,
# используется функция random.choice:

# choice(a, size=None, replace=True)

# a — одномерный массив или число для генерации arange(a);

# size — желаемая форма массива (число для получения одномерного массива,
# кортеж — для многомерного; 
# если параметр не задан, возвращается один объект);

# replace — параметр, задающий, могут ли элементы повторяться 
# (по умолчанию могут).

# Выберем случайным образом из списка двоих человек,
# которые должны будут выступить с отчётом на этой неделе.
# Для этого из списка имён
# (опять же, можно передавать в функцию choice не NumPy-массив, а список)
# получим два случайных объекта без повторений
# (логично, что нужно выбрать двух разных людей).
# Сделать это можно вот так:

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['John' 'Ivan']


In [80]:
# На выходе получили массив из двух имён без повторений. 

# Если попытаться получить без повторений массив большего размера,
# чем имеется объектов в исходном, возникнет ошибка:

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [83]:
# Выборка с повторениями используется по умолчанию.
# Она применяется в том случае, когда мы допускаем,
# что объекты могут повторяться.

# Например, получим случайную последовательность,
# которая образуется в результате десяти подбрасываний игральной кости:

choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[1 5 4 6 5 6 3 3 3 4]


In [87]:
# SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

# NumPy генерирует не истинные случайные числа
# (такие числа получаются в результате случайных процессов),
# а псевдослучайные, которые получаются с помощью особых
# преобразований какого-либо исходного числа.
# Обычно компьютер берёт это число автоматически,
# например, из текущего времени в микросекундах
# (на самом деле используются другие ещё менее предсказуемые числа).
# Такое число называют seed (от англ. — «зерно»).

#Самостоятельно задать seed в NumPy можно с помощью функции
# np.random.seed(<np.uint32>).
# Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295).

# Зададим seed и посмотрим, что получится:

np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [92]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))

# При этом запуск одной и той же функции генерации случайных чисел
# несколько  раз после задания seed не приводит к генерации
# одних и тех же чисел. Однако итоговый результат работы
# всегда будет одинаковый в совокупности.

[8 8 3]
[7 7 0]
[4 2 5]


In [ ]:
# ЗАДАНИЕ 9.6

# Не забудьте импортировать numpy и сразу задать seed 2021
import numpy as np
np.random.seed(2021)
# В simple сохранте случайное число в диапазоне от 0 до 1
simple = None
simple = np.random.rand()
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = None
randoms = np.random.uniform(-150, 2021, size=120)
# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
table = None
table = np.random.randint(1, high=101, size=(3,2))
# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = None
even = np.arange(2,17,2)
# Перемешайте числа в even так, чтобы массив even изменился
np.random.shuffle(even)

# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = None
select = np.random.choice(even, size=3, replace=False)
# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = None
triplet = np.random.permutation(select)