In [ ]:
#С векторами в NumPy можно производить арифметические операции: 
# складывать, 
# вычитать, 
# умножать друг на друга, 
# возводить один вектор в степень другого и т. д.

#Операция, применённая к двум векторам, 
# на самом деле применяется поэлементно. 
# То есть при сложении двух векторов 
# первым элементом нового вектора 
# будет сумма первых элементов исходных векторов, 
# вторым — сумма вторых элементов и т. д.

In [1]:
#Произведём сложение двух векторов:

import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [2]:
#Что бы произошло при сложении двух списков? 
# Их элементы просто объединились бы в один список:

list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [3]:
#Чтобы сложить два этих списка поэлементно, 
# нам пришлось бы написать списочное сокращение 
# с применением функции zip():

[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

In [4]:
#Поэлементно умножим два вектора одинаковой длины:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [5]:
#А теперь создадим vec2, который будет на один элемент короче, чем vec1:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
 
vec1 * vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [7]:
#Исключением является случай, когда операция происходит 
# с вектором и одним числом. Например, вектор целиком 
# можно умножить на число или возвести в степень этого числа:

vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2

array([ 0,  1,  4,  9, 16])

In [8]:
#Также векторы можно сравнивать друг с другом поэлементно:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2
#В результате получаем вектор исходной длины из булевых переменных,
# которые соответствуют результату поэлементного сравнения чисел
# из двух векторов.

array([False, False,  True, False])

In [10]:
#Аналогично можно сравнивать вектор с числом:

vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [11]:
#ПРОДВИНУТЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

#Длина вектора, то есть расстояние между его началом и концом,
# [в евклидовом пространстве]
# вычисляется как квадратный корень из суммы квадратов всех его координат. 
vec = np.array([3, 4])

#Для начала воспользуемся формулой: 
# возведём все элементы в квадрат,
# посчитаем их сумму,
# а затем найдём квадратный корень. 

length = np.sqrt(np.sum(vec ** 2))
print(length)

5.0


In [12]:
# Но можно было поступить проще.
# В NumPy есть специальный подмодуль linalg,
# который позволяет производить операции из линейной алгебры.

# Для вычисления длины вектора нам потребуется функция norm:

length = np.linalg.norm(vec)
print(length)

5.0


In [ ]:
# Расстояние между двумя векторами, 
# то есть расстояние между их концами, [в евклидовом пространстве]
# вычисляется как квадратный корень
# из суммы квадратов разностей соответствующих координат.

#→ По сути, расстояние между векторами
# — это длина такого вектора,
# который является разностью этих векторов. 

In [13]:
# Реализуем вычисление расстояния в коде.
# Сначала — «сложным» способом напрямую из формулы:

vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

12.206555615733702

In [14]:
#А теперь применим более простой способ
# — используем уже известную нам функцию np.linalg.norm:

vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [15]:
#Наконец, скалярным произведением двух векторов
# называют сумму произведений их соответствующих координат.

# Реализуем это в коде
# (по-английски скалярное произведение
# называют dot — точечный — или scalar product,
# отсюда и такое название переменной):

vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

250.0

In [16]:
# в NumPy есть множество встроенных функций,
# поэтому возник резонный вопрос:
# можно ли проще и вообще без формул?

# Да! Для этого используют функцию np.dot(x, y):

scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [17]:
# В частности, равенство скалярного произведения нулю
# означает перпендикулярность рассматриваемых векторов:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)
# В целом, скалярное произведение
# часто используется для определения угла между векторами.

0

In [4]:
#Задание 8.4
# Один из них: сумма длин сонаправленных векторов должна быть
# равной длине суммы двух векторов.

# С помощью этого критерия найдите пару сонаправленных векторов.
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

print ((np.linalg.norm(b) +np.linalg.norm(c) ) == np.linalg.norm(b+c))
print ((np.linalg.norm(b) +np.linalg.norm(a) ) == np.linalg.norm(b+a))
print ((np.linalg.norm(a) +np.linalg.norm(c) ) == np.linalg.norm(a+c))



False
False
True


In [5]:
#Задание 8.5
# Найдите пару векторов, расстояние между которыми больше 100.

print (np.linalg.norm(b-c)> 100)
print (np.linalg.norm(a-c)> 100)
print (np.linalg.norm(b-a)> 100)

True
False
False


In [22]:
# Задание 8.6
# Найдите пару перпендикулярных векторов с помощью скалярного произведения 
# (оно должно быть равно нулю).

print (np.dot(b,c) == 0)
print (np.dot(a,c) == 0)
print (np.dot(b,a) == 0)

False
False
False


In [27]:
#БАЗОВЫЕ СТАТИСТИЧЕСКИЕ ФУНКЦИИ ДЛЯ ВЕКТОРОВ 

# Функции np.min и np.max позволяют находить 
# максимальное и минимальное значение в векторе. 
# Их можно записывать как в виде np.min(<vector>),
# так и в виде <vector>.min():

vec = np.array([2,7,18,28,18,1,8,4])
print (vec.min())
print(np.max(vec))

1
28


In [29]:
# Функция mean позволяет посчитать среднее значение.
# Больше не требуется реализовывать её «руками»!

print(vec.mean())
print(np.mean(vec))

10.75
10.75
