In [4]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [2]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([[12, 45, 78],[34, 56, 13],[12, 98, 76]])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [13]:
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int32')

In [14]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [15]:
arr[2] = 2000
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [16]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [17]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [19]:
arr[2] = 'test'

ValueError: invalid literal for int() with base 10: 'test'

In [21]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

In [22]:
#При преобразовании типов данных в массиве не забывайте о том, 
# что часть чисел может потерять смысл, если менять тип данных 
# с более ёмкого на менее ёмкий:

arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([12321, -1234,  3435,  -214,   100])

In [23]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [5]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)



In [6]:
arr.ndim
nd_arr.ndim

2

In [30]:
arr.size
# 5
nd_arr.size

9

In [31]:
arr.shape
# (5,)
nd_arr.shape

(3, 3)

In [32]:
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

In [7]:
#Создадим одномерный массив из пяти элементов:

zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [8]:
#Создадим трёхмерный массив с формой 5x4x3 и типом float32:

zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
print(zeros_3d)

(5, 4, 3)
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#Поэкспериментируем. Создадим массив из пяти чисел от 0 до 4:
np.arange(5)

In [40]:
#Создадим массив от 2.5 до 5:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [41]:
#Создадим массив от 2.5 до 5 с шагом 0.5:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [42]:
#Создадим массив от 2.5 до 5 с шагом 0.5 и с типом float16:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [43]:
#Создадим массив из десяти чисел между 1 и 2:

arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
#Создадим массив из десяти чисел между 1 и 2, не включая 2:

arr = np.linspace(1, 2, 10, endpoint=False)
arr

In [ ]:
#Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step,2))


arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)