In [8]:
# Задание 10.5

from hidden import a, b
# Пишите здесь команды, который помогут
# найти ответы на вопросы
import numpy as np
a = np.int64(a)
b = np.int64(b)
c = a + b

print (c)

ModuleNotFoundError: No module named 'hidden'

In [9]:
# ЗАДАНИЕ 10.6 
# Напишите функцию get_chess, которая
# принимает на вход длину стороны квадрата a
# и возвращает двумерный массив формы (a, a),
# заполненный 0 и 1 в шахматном порядке.
# В левом верхнем углу всегда должен быть ноль.

# Примечание: воспользуйтесь функцией zeros из библиотеки numpy,
# а затем с помощью срезов без циклов
# задайте необходимым элементам значение 1.

# Напоминание: в Python для получения каждого второго элемента
# используется срез [::2]. Подумайте,
# как грамотно применить этот принцип к двумерному массиву.

# Пример:

#get_chess(1)
# array([[0.]])
#get_chess(4)
# array([[0., 1., 0., 1.],
#        [1., 0., 1., 0.],
#        [0., 1., 0., 1.],
#        [1., 0., 1., 0.]])
def get_chess(a):
    import numpy as np
    zeros_arr = np.zeros((a,a), dtype=np.float32)
    zeros_arr[::2,1::2]=1
    zeros_arr[1::2,::2]=1
    return zeros_arr
print(get_chess(6))

[[0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]


In [13]:
# ЗАДАНИЕ 10.7
#Вы разрабатываете приложение для прослушивания музыки. 
# Конечно же, там будет доступна функция перемешивания плейлиста.
# Пользователю может настолько понравиться перемешанная версия плейлиста,
# что он захочет сохранить его копию. Однако вы не хотите хранить в памяти
# новую версию плейлиста, а просто хотите сохранять тот seed,
# с которым он был сгенерирован.

# Для этого напишите функцию shuffle_seed(<array>),
# которая принимает на вход массив из чисел,
# генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1
# (включительно) и возвращает кортеж:
# перемешанный с данным seed массив
# (исходный массив должен оставаться без изменений),
# а также seed, с которым этот массив был получен.

# Пример:

arr = [1, 2, 3, 4, 5]
# shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
# shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)
import numpy as np
def shuffle_seed(array):
    seed_int = np.random.randint(2**32-1,dtype='int64') 
    np.random.seed(seed_int)
    shuffled_arr = np.random.permutation(array)
    return  shuffled_arr, seed_int

print(shuffle_seed(arr))

(array([1, 4, 2, 3, 5]), 1933996845)


In [ ]:
# Напишите функцию min_max_dist,
# которая принимает на вход неограниченное число векторов через запятую.
# Гарантируется, что все векторы, которые передаются, одинаковой длины.

# Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

# Пример:
import numpy as np
from itertools import product
from collections import Counter

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

def min_max_dist(*vecs):
    vars = np.array(list(product(vecs, repeat=2)))      # генерируем массив с парами векторов,  (есть одинаковые пары) 
    diff_arr = vars[:,0]-vars[:,1]                      # вычисляем массив с разницей векторов,  (есть нулевые вектора)
    dists = list(map(np.linalg.norm, diff_arr))         # вычисляем массив с длин векторов, (есть длины равные нулю)
    dists_c = list(Counter(dists).keys())               # создаем список из значений длин, включая один 0
    dists_c.remove(0)                                   # удаляем 0
    return   min(dists_c), max(dists_c), diff_arr
 
print (min_max_dist(vec1, vec2, vec3))

In [14]:
import numpy as np
from itertools import combinations

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

def min_max_dist(*vecs):
    vars = np.array(list(combinations(vecs, 2)))      # генерируем массив с парами векторов, 
    diff_arr = vars[:,0]-vars[:,1]                      # вычисляем массив с разницей векторов, 
    dists = list(map(np.linalg.norm, diff_arr))         # вычисляем массив с длинами векторов, 
    return   min(dists), max(dists)
 
print (min_max_dist(vec1, vec2, vec3))

(5.196152422706632, 10.392304845413264)


In [ ]:
def min_max_dist(*vecs):
    vars = np.array(list(product(vecs, repeat=2)))      # генерируем массив с парами векторов,  (есть одинаковые пары) 
    diff_arr = vars[:,0]-vars[:,1]                      # вычисляем массив с разницей векторов,  (есть нулевые вектора)
    I = diff_arr != 0                                   # создаем индекс булевый массив, True для значений не равных нулю, False для 0
    vec_len = len(vars[0,0])                            # на данном этапе не смог решить проблему несовместимости форм массивов
    ind_arr_len = diff_arr[I].shape
    a = diff_arr[I].reshape(ind_arr_len/vec_len,vec_len)
    dists = list(map(np.linalg.norm, diff_arr))         
    dists_c = list(Counter(dists).keys())               
    dists_c.remove(0)                                   
    return min(dists_c), max(dists_c)vars[I]
 
print (min_max_dist(vec1, vec2, vec3))

In [2]:
# ЗАДАНИЕ 10.9

# Напишите функцию any_normal, которая
# принимает на вход неограниченное число векторов через запятую.
# Гарантируется, что все векторы, которые передаются, одинаковой длины.

# Функция возвращает True, если есть хотя бы одна пара
# перпендикулярных векторов. Иначе возвращает False.

# Пример:
from itertools import combinations
import numpy as np

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

from itertools import combinations
import numpy as np
def any_normal(*vecs):
    vars = np.array(list(combinations(vecs, 2)))
    any_zeros = list(map(np.dot, vars[:,0],vars[:,1])) 
    if 0 in any_zeros: return True
    return False
print(any_normal(vec1, vec2, vec3))

True


In [42]:
#ЗАДАНИЕ 10.10 

#Напишите функцию get_loto(num), генерирующую трёхмерный массив
# случайных целых чисел от 1 до 100 (включительно).
# Это поля для игры в лото.

# Трёхмерный массив должен состоять из таблиц чисел формы 5х5,
# то есть итоговая форма — (num, 5, 5).

# Функция возвращает полученный массив.

#№Пример:

def get_loto(num):
    
    return np.random.randint(101, size=(num,5,5))
print(get_loto(3))
#Результат:

#array([[[ 35,  66,  38,  11,  32],
#       [ 32,   7,  37,  83,  42],
 #      [ 89,  37,  19,  51,  89],
  #     [ 70, 100,  83,   5,  11],
   #    [ 20,  13,  60,  26,  41]],
 #
  #    [[ 23,  49,  76,  44,  43],
   #    [ 59,  63,  99,  92,   2],
    #   [ 83,   4,  25,  73,  19],
     #  [ 10,  18,  40,  11,  21],
      # [ 58,  45,  73,  93,  61]],
 #
  #    [[100,  88,  70,  34,  51],
   #    [  5,  35,  36,  85,  88],
    #   [ 72,  23,  87,  30,  40],
     #  [ 29,  21,  51,  73,  81],
      # [ 91,  19,  87,  60,  27]]])

[[[  3  96  62  17  65]
  [  5  27  68  83  36]
  [ 48  32  85  95  10]
  [ 72  41  65  51  97]
  [ 66  91  76  83  69]]

 [[ 51 100  90  50  34]
  [  7  92  88  41   7]
  [  1  85  67  69  74]
  [ 54   6  83  79  16]
  [ 16  64  95  54  95]]

 [[ 89  80  13  90  92]
  [ 56  15  96  80  99]
  [ 70  49  57  79   3]
  [ 12  61   4  37  23]
  [  5  33  65  76  76]]]


In [49]:
def get_loto(num):
    
    return np.random.randint(101, size=(num,5,5))

In [64]:
# ЗАДАНИЕ 10.11 

#Напишите функцию get_unique_loto(num).
# Она так же, как и функция в задании 10.10,
# генерирует num полей для игры в лото,
# однако теперь на каждом поле 5х5 числа не могут повторяться.

#Функция также должна возвращать массив формы num x 5 x 5.

#Пример:

def get_unique_loto(num):
    unique_loto = np.random.choice(np.arange(1,101), size=(num,5,5), replace=False)
    return unique_loto
print(get_unique_loto(3))
#Результат:

#array([[[26, 91, 73,  7, 16],
 #      [46, 85, 78, 77, 51],
  #     [84, 86, 55, 71, 58],
   #    [17, 61, 50, 30, 97],
    #   [66, 29, 38, 41, 32]],
 #
  #    [[49, 32,  3, 21, 85],
   #    [45,  8, 94, 46, 96],
    #   [41, 38, 58, 37, 98],
     #  [66, 77, 54, 80, 26],
      # [62, 63, 72,  5, 43]],
 #
  #    [[55, 60,  6, 80, 97],
   #    [23, 69, 94,  9, 24],
    #   [17, 98, 27, 63, 79],
     #  [84, 74, 51, 39, 54],
      # [77, 30, 48, 75, 85]]])

[[[  3  77  87  27  57]
  [ 66  76  97  74  28]
  [ 51  71  26  10  64]
  [ 33  94   8  22  15]
  [ 19  36  96  75   7]]

 [[ 68  38  82  72  30]
  [ 47  85  59  58  13]
  [ 32  50  20 100   2]
  [ 24  81  53  80  45]
  [ 23  65  56  44  88]]

 [[ 18  16  84  99  21]
  [ 95  31  11  35  62]
  [ 42  67  55  93  14]
  [ 92  46  60  98  48]
  [  9  69  52  40  25]]]


In [1]:
simplelist = [19, 242, 14, 152, 142, 1000]
np.mean(simplelist)

NameError: name 'np' is not defined